# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bWbGT-6Hvm5cv2NkwFgIlOODVmniNrLB
"""

#STUDENT_NAME: ABDUL REHMAN
#PROJECT: COUNTDOWN TIMER

import time

def countdown(t):

    while t:

        mins, secs = divmod(t, 60)

        timer = '{:02d}:{:02d}'.format(mins, secs)

        print(timer, end="\n")

        time.sleep(1)

        t -= 1

    print('Lift off!')

t = input("Enter the time in seconds: ")

countdown(int(t))

